# Generated by Django 5.0.7 on 2025-03-25 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0002_alter_course_thumble'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_list', models.JSONField(blank=True, default=list)),
                ('enroll_date', models.DateField(auto_now_add=True)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='accounts.student')),
            ],
        ),
    ]
