# Generated by Django 5.0.7 on 2025-03-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progressions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progres',
            old_name='courses',
            new_name='course',
        ),
    ]
