# Generated by Django 5.0.7 on 2025-01-31 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, default=None, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, default='https://www.facebook.com/', max_length=100, null=True)),
                ('twitter', models.URLField(blank=True, default='https://www.x.com/', max_length=100, null=True)),
                ('linkedin', models.URLField(blank=True, default='https://www.linkedin.com/', max_length=100, null=True)),
                ('title', models.TextField(blank=True, max_length=60, null=True)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('expertise', models.CharField(blank=True, max_length=255, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, default='https://www.google.com/', max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, default=None, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, default='https://www.facebook.com/', max_length=100, null=True)),
                ('twitter', models.URLField(blank=True, default='https://www.x.com/', max_length=100, null=True)),
                ('linkedin', models.URLField(blank=True, default='https://www.linkedin.com/', max_length=100, null=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='students', to='courses.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
