# Generated by Django 5.0.7 on 2025-01-31 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('thumble', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('total_lecture', models.IntegerField(blank=True, null=True)),
                ('total_session', models.IntegerField(blank=True, null=True)),
                ('total_length', models.IntegerField(blank=True, null=True)),
                ('total_student', models.PositiveIntegerField(default=0)),
                ('category', models.ManyToManyField(related_name='course', to='courses.category')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('order', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=150)),
                ('duration', models.CharField(blank=True, max_length=8, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
