# Generated by Django 5.0.7 on 2025-01-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumble',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
